### ISSUE TITLE
"Could not find a part of the path" error occurs when a file exists in pending changes but doesn't exist on disk

### ISSUE THREAD

**Issue by icnocop** [dprZoft/shelvesetcomparer#10]
Hi.

Thank you for `DiffFinder for VS2022`! 🙏

When I try to find the differences between a shelveset and my pending changes, I get the following error message in the "General" output window:
```
12/1/2023 10:50:41 PM Open TeamExplorer ShelvesetComparer page with WS: ComputerName;FirstName LastName
12/1/2023 10:50:53 PM Microsoft.TeamFoundation.VersionControl.Client.VersionControlException: C:\Work\TeamProject\branch\Solution1\Project1\File1.cs: Could not find a part of the path 'C:\Work\TeamProject\branch\Solution1\Project1\File1.cs'. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Work\TeamProject\branch\Solution1\Project1\File1.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.TeamFoundation.VersionControl.Client.UploadDownload.UploadPrepareContentStreamCallback(Object ar)
   --- End of inner exception stack trace ---
   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.UploadChanges(IEnumerable`1 changes, Boolean saveUploadedContentAsBaselines, UploadedBaselinesCollection& uploadedBaselinesCollection, OnProcessingChangeDelegate onPendingMethod, Int32 operationId)
   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.ShelveInternal(Shelveset shelveset, PendingChange[] changes, ShelvingOptions options, Int32 operationId)
   at Microsoft.TeamFoundation.VersionControl.Client.Workspace.Shelve(Shelveset shelveset, PendingChange[] changes, ShelvingOptions options)
   at DiffFinder.SelectShelvesetSection.FetchPendingChangeShelveset(ITeamFoundationContext context, Workspace ws)
   at DiffFinder.SelectShelvesetTeamExplorerView.CompareWithPendChangeButtons_Click(Object sender, RoutedEventArgs e)
12/1/2023 10:50:53 PM C:\Work\TeamProject\branch\Solution1\Project1\File1.cs: Could not find a part of the path 'C:\Work\TeamProject\branch\Solution1\Project1\File1.cs'.
```

The "Diff Finder" window does not appear.
That file is in my pending changes window, but in "Excluded Changes".
That file doesn't exist on disk.
I expected DiffFinder to log a warning message and continue.

Thank you.

**Comment by icnocop** [comment]
As a work-around, I have to undo the pending changes for that file.
